### ISSUE TITLE
No description provided

### ISSUE THREAD

**Issue by Duzhinsky** [Dereden399/weather-page#1]
![image](https://github.com/Dereden399/weather-page/assets/27966070/bd093fc6-94c4-4ea4-99e7-ac6f5f7d3a83)

**Comment by Dereden399** [comment]
Added meaningful description

**Comment by Duzhinsky** [comment]
![image](https://github.com/user-attachments/assets/a9749641-5b18-4d3e-93b0-53838c228058)
